### ISSUE TITLE
CPU frequency not avaible in Linux 5.X 

### ISSUE THREAD

**Issue by enricocovili** [Peppe289/RK-manager#3]
I run into this problem while executing the program:
![immagine](https://user-images.githubusercontent.com/69142763/163441653-ea3de971-115b-4d70-abb3-08b6d117ffca.png)

This issue probably relates to:
* https://github.com/torvalds/linux/blob/f400bea2d44beec76f7e7f45e5372ef790336a4d/tools/power/cpupower/lib/cpufreq.c#L75
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/tools/power/cpupower/lib/cpufreq.c?h=linux-5.10.y#n75

**Comment by Peppe289** [comment]
removed with this commit. I'll adjust based on the frequency multiplier

https://github.com/Peppe289/RK-Manager/commit/1a6f22e677ce6e36cf6b6401862dfe5fe955f944

**Comment by NextWork123** [comment]
Peppe is much uselss he removed the commit but not fixed that

**Comment by Peppe289** [comment]
> 

I will fix your brain. wait some year's
